[package]
name = "monitor"
version = "0.0.1"
authors = ["CCA Contributors"]
edition = "2018"

[lib]
name = "monitor"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
linked_list_allocator = "0.9.1"
spinning_top = "0.2.4"
lock_api = "=0.4.3"
spin = "0.9.2"
log = "0.4.17"
