[package]
name = "fvp"
version = "0.0.1"
authors = ["CCA Contributors"]
edition = "2018"

[[bin]]
name = "fvp"
path = "src/main.rs"

[dependencies]
armv9a = { path = "../../armv9a" }
bitflags = "1.3"
linked_list_allocator = "0.10.4"
log = "0.4.17"
monitor = { path = "../../monitor" }
uart = { path = "../../../lib/uart" }

[build-dependencies]
cc = "1.0"
